image: registry.gitlab.com/bednic/json-api/ci:7.3

stages:
    - build
    - test

build:
    stage: build
    script:
        - composer -q install
    artifacts:
        paths:
            - vendor

test:unit:
    stage: test
    script:
        - vendor/bin/phpunit
