image: bednic/php-runtime:7.4

stages:
    - build
    - test
    - analyse
    - docs

variables:
    SONAR_HOST_URL: "https://sonarcloud.io"
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"

build:
    stage: build
    script:
        - composer -q install
        - composer validate --no-check-all --strict
    artifacts:
        paths:
            - vendor

test:unit:
    stage: test
    script:
        - vendor/bin/phpunit
    artifacts:
        paths:
            - tmp

code_sniffer:
    stage: analyse
    script:
        - vendor/bin/phpcs

sonar:
    stage: analyse
    only:
        - '/^[0-9]+\.x/'
    image:
        name: sonarsource/sonar-scanner-cli:latest
        entrypoint: [""]
    cache:
        key: "${CI_JOB_NAME}"
        paths:
            - .sonar/cache
    script:
        - sonar-scanner
    allow_failure: true
    dependencies:
        - test:unit

phpstan:
    stage: analyse
    script:
        - vendor/bin/phpstan -n --no-ansi analyse

pages:
    stage: docs
    only:
        - tags
    image:
        name: phpdoc/phpdoc:3
        entrypoint: [""]
    services: [ ]
    script:
        - phpdoc -d src -t public
    artifacts:
        paths:
            - public
        expire_in: 1h
