<?php

declare(strict_types=1);

namespace JSONAPI\Test\Factory;

use JSONAPI\Configuration;
use JSONAPI\Document\Builder;
use JSONAPI\Driver\AnnotationDriver;
use JSONAPI\Document\BuilderFactory;
use JSONAPI\Metadata\MetadataFactory;
use JSONAPI\Metadata\MetadataRepository;
use JSONAPI\URI\URIParser;
use PHPUnit\Framework\TestCase;
use Slim\Psr7\Factory\ServerRequestFactory;
use Symfony\Component\Cache\Adapter\ArrayAdapter;
use Symfony\Component\Cache\Psr16Cache;

class DocumentBuilderFactoryTest extends TestCase
{
    public static MetadataRepository $metadata;
    /**
     * @var Configuration configuration
     */
    private static Configuration $configuration;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        self::$metadata      = MetadataFactory::create(
            [RESOURCES . '/valid'],
            new Psr16Cache(new ArrayAdapter()),
            new AnnotationDriver()
        );
        self::$configuration = new Configuration(self::$metadata, 'http://unit.test.org');
    }

    public function testNew()
    {
        $request  = ServerRequestFactory::createFromGlobals();
        $factory  = new BuilderFactory(self::$configuration);
        $composer = $factory->create($request);
        $this->assertInstanceOf(Builder::class, $composer);
    }
}
